version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasks
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - JWT_SECRET_KEY=jwt-secret-key
      - SECRET_KEY=super-secret-key
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - backend
      - redis

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
